# .air.toml

# Project root directory
root = "."

# Temporary directory for builds
tmp_dir = "tmp"

[build]
  # Command to build your app
  cmd = "go build -o ./bin/go-http-template ./cmd"

  # Binary to run after build
  bin = "./bin/go-http-template"

  # File extensions to watch for changes
  include_ext = ["go", "tpl", "tmpl", "html"]

  # Directories to exclude from watching
  exclude_dir = ["assets", "bin", "tmp", "vendor"]

  # Delay in ms before restarting after a change
  delay = 100

  # Signal to kill the running process
  kill_signal = "SIGINT"

  # Timeout before force killing process
  kill_timeout = 5000

  # Delay in ms before restarting after killing
  restart_delay = 100
